### ISSUE TITLE
For fun it would be neat to see this run against llama-2-7b

### ISSUE THREAD

**Issue by adamsch1** [karpathy/llama2.c#46] opened 2023-07-24 20:55 UTC
Any tips on how to try that out?

**Comment by adamsch1** [comment] 2023-07-24 20:55
Also thanks for sharing, it's a really useful learning tool reading the code.

**Comment by dontgetfoundout** [comment] 2023-07-24 23:37
It should be possible to port the `export()` function from the `Transformer` class in [model.py](https://github.com/karpathy/llama2.c/blob/master/model.py#L320) to Llama's implementation and export a compatible model from there.  I modified their `Llama.build()` function (https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L98C66-L98C66) to export the model on startup.

Unfortunately, the model is not generating meaningful output with llama2.c for me at the moment and I haven't had the chance to debug it yet.  Andrej mentions in the README that it should be possible to load their weights and it's "working" well enough to make me think that's true.  I should have some more time to debug later tonight.

For example:

```
$ OMP_NUM_THREADS=4 ./run ../llama/model-llama2-7b.bin 0.6 128
<s>
 hinadating Neu Neu Neu Neu Federation Federationчо caught зе rende Bruce Bruce Bruce Bruce Bruce Bruce Bruce Bruce pas pass Pass Pass effet merc merc merc Vitt Vitt Vitt Vitt Vitt Vitt Vitt VittbazFL pubblic habe habe habe beach beach Пор WHERE Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt liga Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt depos Rum rum Rum Rum Void€abama fier fier fierיêmeême habe habe Sony Sony Sony Sony Sony cher myst myst myst Zam Zam Zam Zam Zam Zam Zam Zam Zam Zam АрхивнаяnewNEW expose exposeaffenaffenaffenaffenaffenaffenaffenaffenaffenaffenaffenaffenaffen habe habe
achieved tok/s: 2.851828
```  

For comparision, the same run binary with Andrej's 44m model:

```
$ OMP_NUM_THREADS=4 ./run out/model44m.bin 0.9 128
<s>
 Once upon a time, there was a little boy named Timmy. Timmy loved to play outside, but one day he got lost in the woods. He was scared and didn't know what to do. Suddenly, he saw a knight with a big sword! The knight was brave enough to save Timmy and take him back home.
But then, Timmy remembered something he did earlier that day. He had taken his sister's favorite toy without asking. He felt guilty and didn't know what to do. So, he decided to surrender and go back to the knight.

achieved tok/s: 1828.571429
```

**Comment by karpathy** [comment] 2023-07-24 23:56
@dontgetfoundout I am suspicious of the Linears atm, RowLinear vs ColLinear etc. Taking a look...

**Comment by karpathy** [comment] 2023-07-25 03:02
I found it. Llama2 does not share weights between the embeddings and the classifier weights. My code assumes these are shared. Fixing...

**Comment by adamsch1** [comment] 2023-07-25 03:59
> It should be possible to port the `export()` function from the `Transformer` class in [model.py](https://github.com/karpathy/llama2.c/blob/master/model.py#L320) to Llama's implementation and export a compatible model from there. I modified their `Llama.build()` function (https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L98C66-L98C66) to export the model on startup.
> 
> Unfortunately, the model is not generating meaningful output with llama2.c for me at the moment and I haven't had the chance to debug it yet. Andrej mentions in the README that it should be possible to load their weights and it's "working" well enough to make me think that's true. I should have some more time to debug later tonight.
> 
> For example:
> 
> ```
> $ OMP_NUM_THREADS=4 ./run ../llama/model-llama2-7b.bin 0.6 128
> <s>
>  hinadating Neu Neu Neu Neu Federation Federationчо caught зе rende Bruce Bruce Bruce Bruce Bruce Bruce Bruce Bruce pas pass Pass Pass effet merc merc merc Vitt Vitt Vitt Vitt Vitt Vitt Vitt VittbazFL pubblic habe habe habe beach beach Пор WHERE Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt liga Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt Vitt depos Rum rum Rum Rum Void€abama fier fier fierיêmeême habe habe Sony Sony Sony Sony Sony cher myst myst myst Zam Zam Zam Zam Zam Zam Zam Zam Zam Zam АрхивнаяnewNEW expose exposeaffenaffenaffenaffenaffenaffenaffenaffenaffenaffenaffenaffenaffen habe habe
> achieved tok/s: 2.851828
> ```
> 
> For comparision, the same run binary with Andrej's 44m model:
> 
> ```
> $ OMP_NUM_THREADS=4 ./run out/model44m.bin 0.9 128
> <s>
>  Once upon a time, there was a little boy named Timmy. Timmy loved to play outside, but one day he got lost in the woods. He was scared and didn't know what to do. Suddenly, he saw a knight with a big sword! The knight was brave enough to save Timmy and take him back home.
> But then, Timmy remembered something he did earlier that day. He had taken his sister's favorite toy without asking. He felt guilty and didn't know what to do. So, he decided to surrender and go back to the knight.
> 
> achieved tok/s: 1828.571429
> ```
Thanks for the response!  I see so basically crib the export function in model.py and call it inside the official llama code at startup to you get it dumped in the right format?

**Comment by dontgetfoundout** [comment] 2023-07-25 04:08
> I found it. Llama2 does not share weights between the embeddings and the classifier weights. My code assumes these are shared. Fixing...

Awesome.  That makes perfect sense.  I just got back to my computer.  Let me know if I can help test out any changes.  


> Thanks for the response! I see so basically crib the export function in model.py and call it inside the official llama code at startup to you get it dumped in the right format?

Yep.  You got it.  It sounds like Andrej has a fix in the works for inference on these models.  As an FYI, there's a possibility that export function (and as a result the model output) will change as a result of his fix.  I haven't had the chance to investigate the issue more closely, but he says the issue is a result of weight sharing and the export function has this comment:

```
# note: no need to write final classifier weights due to weight sharing
```

If you're paying for the compute to build the model, you may want to wait for the fix.

**Comment by karpathy** [comment] 2023-07-25 04:21
BAM https://github.com/karpathy/llama2.c/commit/c3e0d73bd294e1f5e4d17425fac09aaec536400d

EXPLOSION EMOJI :D

**Comment by karpathy** [comment] 2023-07-25 04:48
Closing this issue. Let's now create the next issue for chatting with Llama 2 7B Chat 😅 ...

**Closed by karpathy** 2023-07-25 04:48 UTC

**Comment by dontgetfoundout** [comment] 2023-07-25 05:49
It works!  In the spirit of the tinystories model I prompted it with `"<s>Once upon a time there was"`

```
$ OMP_NUM_THREADS=4 ./run ../llama/llama2_7b.bin 0.6 128
<s>
Once upon a time there was |> a little boy who lived in the woods. He was very lonely and would spend many hours out in the forest playing by himself. One day this little boy was playing near a tree when something caught his eye. He noticed a large, shiny object near the base of the tree. He walked over to it and discovered it was a key. The boy was very curious and decided to take it home with him.
When he got home, he opened the key and to his surprise, it opened a door that had been hidden all this time. The boy walked through the door and found himself in a
achieved tok/s: 43.525849
```

**Comment by karpathy** [comment] 2023-07-25 05:56
🔥!! note that the tok/s is misreported :( Have to fix that.
